### ISSUE TITLE
Add Microdata (to RDF) parser?

### ISSUE THREAD

**Issue by bergos** [rdf-ext/rdf-parser-microdata#1]
_From @danbri on October 19, 2014 18:54_

There's a lot of Microdata out there (mostly schema.org); it parses to RDF fairly simply. Any plans for a parser? I don't have a tool to recommend, although http://www.milowski.com/journal/entry/2013-07-26T15:25:04.782Z/ might be interesting.

_Copied from original issue: rdf-ext/rdf-ext#5_

**Comment by bergos** [comment]
_From @elf-pavlik on October 19, 2014 20:19_

:+1: Green Turtle should handle parsing both Microdata and RDFa

@alexmilowski would you consider also releasing it on NPM? https://github.com/alexmilowski/green-turtle/issues/3
jsonld.js 'bundles' it and already uses in node environment!

**Comment by bergos** [comment]
_From @danbri on October 19, 2014 21:29_

I have vague memory of Green Turtle not working for everyone (Node.js etc) since it assumes presence of a browser-based DOM. Is that correct?

**Comment by bergos** [comment]
_From @elf-pavlik on October 19, 2014 22:3_

I'll check what jsonld.js does but it looks like they have it working in node
https://github.com/digitalbazaar/jsonld.js/blob/master/js/rdfa.js#L11-L19

I had problem the other way, with running jsonld.js in a browser via browserify since it requires _jsdom_ for parsing RDFa
https://github.com/digitalbazaar/jsonld.js/blob/master/js/request.js#L94-L104

IMO we could sort it out without very laborious efforts...

@bergos what rdflib.js uses for parsing XML in node? I also see _jsdom_ in its package.json
https://github.com/linkeddata/rdflib.js/blob/master/package.json#L15

**Comment by bergos** [comment]
_From @ktk on October 28, 2014 8:46_

@elf-pavlik the Node.js version of rdflib.js was done by Melvin Carvalho, see my comment in an old issue of RDFStore:  https://github.com/antoniogarrote/rdfstore-js/pull/31

**Comment by bergos** [comment]
I added a Microdata parser based on the Green Turtle code (only tested with node at the moment!). I used the first schema.org/Person [1] example for testing. I expected the absolute URL values, as defined in the spec [2], to be named nodes. pyMicrodata does it that way (tried with [3]). I patched the js code to produced named nodes. The JSON-LD example at schema.org [1] uses literals. So what's right? Creating named nodes makes more sense to me.

[1] http://schema.org/Person
[2] http://www.w3.org/TR/microdata/#values
[3] http://rdf-translator.appspot.com/

**Comment by bergos** [comment]
_From @gkellogg on November 4, 2014 16:21_

@bergos Great work! Note the Microdata to RDF test suite [1]. Also, note that we're starting to update the Microdata to RDF spec [2] to simplify it and fix some issues [3].

[1] https://dvcs.w3.org/hg/htmldata/raw-file/default/microdata-rdf/tests/index.html
[2] http://www.w3.org/TR/microdata-rdf/
[3] https://github.com/w3c/microdata-rdf

**Comment by bergos** [comment]
Thanks for the hint @gkellogg. With the latest test data updates the number of failed tests is now 32 [1]. I will try to fix them soon to make an npm version with official Microdata support.

[1] https://www.bergnet.org/people/bergi/files/documents/2014-11-11/index.html

**Comment by bergos** [comment]
_From @gkellogg on November 16, 2014 15:38_

FYI, some of your issues may go away with the upcoming update [[1]](http://w3c.github.io/microdata-rdf). We'll send that out for public comment soon. Also note the new test suite [[2]](http://w3c.github.io/microdata-rdf/teats).

**Comment by bergos** [comment]
_From @elf-pavlik on January 20, 2015 20:50_

@bergos have you tried to parse RDFa with Green Turtle?
jsonld.js bundles it for that reason https://github.com/digitalbazaar/jsonld.js/blob/master/js/rdfa.js

**Comment by bergos** [comment]
@elf-pavlik the idea was first to add the Green Turtle Microdata parser with some small changes to RDF-Ext and than to reuse the patched code to get the RDFa parser running. But I had to patch so much in the Microdata parser that I decided to rewrite most of the code based on the spec. Now I'm not sure which version is better/worse, because writing the parser based on the spec wasn't a big success. Long story short: I'm working on the Microdata parser and than comes the RDFa parser on my todo list :-)

**Comment by bergos** [comment]
_From @elf-pavlik on January 21, 2015 0:17_

Wow! Looks like you have an adventure with this one @bergos :wink:

I think RDFa should make much less of a challenge since it boils down to parsing one of standard RDF serializations. See https://github.com/digitalbazaar/jsonld.js/blob/master/js/request.js#L117

Anyways, eventually I will need both to test examples in ActivityStreams2.0 specs https://github.com/jasnell/w3c-socialwg-activitystreams/issues/65 , but RDFa would give me third one for comparing with JSON-LD and Turtle...

**Comment by bergos** [comment]
_From @danbri on January 21, 2015 9:56_

So is the conclusion that green tortoise does not require a real browser DOM, just a basic .js environment?

**Comment by bergos** [comment]
@danbri Green Turtle requires DOM, but the https://www.npmjs.com/package/xmldom implementation can be used. xmldom was already in the RDF-Ext dependency list, because the RDF/XML parser also requires DOM.

**Comment by bergos** [comment]
@elf-pavlik I added a RDFa parser based on the JSON-LD code. At the moment it works only in a Node.js like environment. The JSON-LD require.js is a Node.js program. So I'm not sure if the JSON-LD code works without patching in the browser. Problem: The DOMParse class + .parseFromString method don't have a baseURI parameter, but the rdfa.js code requires a dom.baseURI or dom.location.href property, but that's read-only in the browser. Also language support doesn't work. I tried jsdom and xmldom. Sorry that I don't have a better solution at the moment. I hope it's usefull the way it is at the moment.

**Comment by bergos** [comment]
_From @elf-pavlik on February 27, 2015 11:44_

@bergos thank you! I just added few days ago a very rought parsing of RDFa to Activity Streams 2.0 spec in this commit https://github.com/elf-pavlik/w3c-socialwg-activitystreams/commit/4e79eb138157acd7f0157315de848bb8d22447ea

I'll try to talk with @alexmilowski and @davidlehn | @dlongley about creating proper NPM rdfa package based on green-turtle and also using it as dependency in jsonld
- https://github.com/alexmilowski/green-turtle/issues/3
- https://github.com/digitalbazaar/jsonld.js/issues/41#issuecomment-29796442
- https://lists.w3.org/Archives/Public/public-rdfjs/2014Jan/0014.html

cheers!

**Comment by danbri** [comment]
Great work, thanks for all the updates :) I wonder what the most important differences between xmldom and 'real' browser DOMs are. Does it handle HTML5-style non-XML DOMs, or can that be patched in with some other library? The vast majority of microdata-carrying pages aren't XML-friendly and have all kinds off ugly but recoverable errors that a standard html5 parser would protect us from.

**Comment by bergos** [comment]
@alexmilowski joined the [Representation Task Force](https://github.com/rdfjs/representation-task-force). Version 1.x of RDF-Ext will use the new interfaces and will no longer need a wrapper around [Green Turtle](https://github.com/alexmilowski/green-turtle).
